dataSources:
  - executor: YoutubeCrawler
processingStages:
  - executor: Filterer
  - executor: Filterer
    config:
      filter_str: 'is_cancelled != 1'
  - executor: Filterer
    config:
      filter_str: "tags['state'] != 'in-progress'"
  - executor: AutoLabeler
    config:
      key: "state"
      val: "in-progress"
  - executor: UniversalDownloader
  - executor: Printer
  - executor: Splitter
  - executor: Labeler
  - executor: AutoLabeler
  - executor: Printer
    config:
      msg: "labelling complete"
  - executor: LocalStorageUpdater
