language: python
cache: pip
matrix:
  include:
    - os: linux
      name: Linux Test
      python: 3.8
      script:
        - cd lib/anonymization
        - git checkout autodash
        - cd -
        - python -m pip install --upgrade pip
        - pip install -r requirements.txt
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/xerus-media; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmediainfo-dev; fi
        - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
        - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi
        - ./tools/run_tests.sh