dataSources:
  - executor: FirebaseSource
  - executor: RedditCrawler
  - executor: YoutubeCrawler
processingStages:
  - executor: Printer
    config:
      msg: "firebase src complete"
  - executor: Filterer
  - executor: UniversalDownloader
  - executor: Printer
  - executor: ObjectDetector
  - executor: Labeler
  - executor: AutoLabeler
  - executor: FirebaseUpdater
