- - executor: database.FirebaseSource.FirebaseSource
- - executor: executor.Printer.Printer
    config:
      msg: "firebase src complete"
- - executor: downloader.UniversalDownloader.UniversalDownloader
- - executor: executor.Printer.Printer
- - executor: executor.FaceBlurrer.FaceBlurrer
- - executor: executor.labeler.Labeler
