dataSources:
  - executor: .database.FirebaseSource.FirebaseSource
processingStages:
  - executor: .executor.Printer.Printer
    config:
      msg: "firebase src complete"
  - executor: UniversalDownloader.UniversalDownloader
  - executor: Printer
  - executor: ObjectDetector
    config:
      model_id: faster_rcnn_resnet101_kitti_2018_01_28
      skip_n: 60
      batch_size: 10
      confidence_threshold: 0.85
  - executor: DeferTaskExecutor
