dataSources:
  - executor: FirebaseSource
processingStages:
  - executor: Printer
    config:
      msg: "firebase src complete"
  - executor: UniversalDownloader
  - executor: Printer
  - executor: ObjectDetector
    config:
      model_id: faster_rcnn_resnet101_kitti_2018_01_28
      skip_n: 60
      batch_size: 10
      confidence_threshold: 0.85
  - executor: DeferTaskExecutor
